[package]
name = "pwa-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
neutralipcrs = ">=1.3.0, <1.4.0"
actix-web = "4.4"
actix-files = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
