[package]
name = "neutralts-rocket"
version = "0.0.0"
edition = "2021"

[dependencies]
neutralts = { path = "../../" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rocket = "0.5"
rocket_http = "0.5.1"
