[package]
name = "pwa-warp"
version = "0.1.0"
edition = "2021"

[dependencies]
neutralts = ">=1.3.0, <1.4.0"
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
