[package]
name = "neutral-webapp"
version = "0.0.0"
edition = "2021"

[dependencies]
neutralts = { path = "../../" }
actix-web = "4.9.0"
actix-files = "0.6.6"
serde_json = "1.0"
url = "2"
serde_urlencoded = "0.7.1"
